dist: trusty
sudo: required

language: android

jdk:
  - openjdk8

before_install:
  # Install SDK license so Android Gradle plugin can install dependencies.
  - mkdir "$ANDROID_HOME/licenses" || true
  - echo "24333f8a63b6825ea9c5514f83c2829b004d1fee" > "$ANDROID_HOME/licenses/android-sdk-license"

script:
  - ./gradlew testFlossDebugUnitTest evaluateViolations -s

cache:
  directories:
    - $HOME/.gradle
    - $HOME/.android
