---
project_identifier: devwidget

files:
  - source: '**/src/main/res/values/*_strings.xml'
    translation: '**/src/main/res/values-%android_code%/%original_file_name%'
    ignore: ['**/pref_key_strings.xml']
    languages_mapping:
      android_code:
        tr: tr
